"project_id_env": "1"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://coupang.api.crowdin.com"
"preserve_hierarchy": true
files: [
  {
    "source": "/resources/en/*.json",
    "translation": "/resources/%two_letters_code%/*.json",
  }
]